# Generated by Django 4.1.1 on 2022-10-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_comment_article"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="category",
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(related_name="article", to="home.category"),
        ),
    ]
