# Generated by Django 4.1.1 on 2022-10-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_article_category_article_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
