# Generated by Django 4.1.1 on 2022-10-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_alter_article_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                default="uploads/articles/noimage.png",
                null=True,
                upload_to="uploads/articles/",
            ),
        ),
    ]
