# Generated by Django 4.1.1 on 2022-10-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
