# Generated by Django 4.1.1 on 2022-10-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_comment_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
