# Generated by Django 4.1.1 on 2022-10-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_alter_comment_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                default="..static/noimage.png", null=True, upload_to="uploads/articles/"
            ),
        ),
    ]
