# Generated by Django 4.1.1 on 2022-10-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pfp",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/pfp/"),
        ),
    ]
