# Generated by Django 4.1.1 on 2022-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authuser", "0003_alter_profile_pfp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="pfp",
            field=models.ImageField(
                default="../static/noimage.png", null=True, upload_to="uploads/pfp/"
            ),
        ),
    ]
